services:
  api:  
    build:
      dockerfile: Dockerfile
    container_name: app_api
    #env_file: .env
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=api.xoailac.top
      - LETSENCRYPT_HOST=api.xoailac.top
      - LETSENCRYPT_EMAIL=ml2673572@gmail.com
      - VIRTUAL_PORT=8080
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    external: true
    name: app-network