services:
  api:  
    build:
      # context: ./api.movie28.com
      dockerfile: Dockerfile
    container_name: app_api
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge