services:
  api:  
    build:
      dockerfile: Dockerfile
    container_name: app_api
    #env_file: .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    external: true
    name: app-network